### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [Remiccino/catpuccino#31]
Hi,<br><br>url : https://github.com/Remiccino/catpuccino/blob/15de5680f41d1becc4c4e964e79138e04fe317db/magic.txt <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by Remiccino** [comment]
Hi, 
Thanks for the heads up. that password (and this repo) is obsolete now though, but I removed the file just in case. Thanks :)
